(function(f){var h={UNDEFINED:0,BUILDED:1,LOADED:2,INITED:3},n={},j={},l=0,a=function(m){if(n[m])return n[m];var m=m.split("."),a=window,c;for(c in m){if(!(m[c]in a))return f;a=a[m[c]]}return a},c=function(c){return(c=a(c))?c.packageStatus:h.UNDEFINED},e=function(c,g,b){"string"===typeof c&&(c=a(c));var i={},f=a("Z");if(g)for(var k in g)i[k]=a(g[k]);b&&b.call(c,f,i);c.packageStatus=h.INITED;c=c.packageName;if(g=j[c]){for(i=0;i<g.length;i++)b=g[i],d(b.requirePackages)&&e(b.packageName,b.requirePackages,
b.constructor);delete j[c]}},d=function(a){if(!a)return!0;var b,e;for(e in a)if(b=a[e],c(b)!==h.INITED)return!1;return!0},b=function(){var c,a,b;c=arguments[0];3===arguments.length?(a=arguments[1],b=arguments[2]):2===arguments.length?b=arguments[1]:(c="Z.anonymous."+l++,b=arguments[0]);var i;i=c;var f=n[i];if(!f){var f=window,k=i.split("."),o;for(o in k)k[o]in f||(f[k[o]]={}),f=f[k[o]];n[i]=f}if(!("packageName"in f))f.packageName=i;if(!("packageStatus"in f))f.packageStatus=h.BUILDED;i=f;if(i.packageStatus===
h.BUILDED)i.packageStatus=h.LOADED;if(a&&!d(a))for(var p in a)i=a[p],j[i]||(j[i]=[]),j[i].push({packageName:c,requirePackages:a,constructor:b});else e(i,a,b)};b("Z",function(e){e.PACKAGE_STATUS=h;e.$package=b;e.getPackage=a;e.getPackageStatus=c})})();
Z.$package("Z",function(f){this.debug=function(a){window.console&&(console.debug?console.debug(a):console.log(a))};var h=Object.prototype.toString;this.is=function(a,c){var e=h.call(c).slice(8,-1);return void 0!==c&&null!==c&&e===a};this.isString=function(a){return"[object String]"===h.call(a)};this.isArray=Array.isArray||function(a){return"[object Array]"===h.call(a)};this.isArguments=function(a){return"[object Arguments]"===h.call(a)};this.isObject=function(a){return"[object Object]"===h.call(a)};
this.isFunction=function(a){return"[object Function]"===h.call(a)};this.isUndefined=function(a){return"[object Undefined]"===h.call(a)};this.isEmpty=function(a){if(a){if(this.isArray(a))return!!a.length;for(var c in a)return!1;return!0}return!1};var n=this.isSameObject=function(a,c,e){if(a===c||!a&&!c)return!0;for(var d in a)if(a.hasOwnProperty(d))if(f.isObject(a[d])&&f.isObject(c[d])&&e){if(!n(a[d],c[d],e))return!1}else if(a[d]!==c[d])return!1;return!0},j=function(a,c,e){for(var d=arguments,b,m=
1;m<d.length;m++){b=d[m];for(var g in b)a[g]=f.isArray(b[g])?b[g].concat():f.isObject(b[g])?a[g]&&f.isArray(a[g])?j({},b[g]):j({},a[g],b[g]):b[g]}return a},l=function(a){if(f.isArray(a))return a.concat();if(f.isArguments(a)){for(var c=[],e=0,d;d=a[e];e++)c.push(l(d));return c}return f.isObject(a)?j({},a):a};this.merge=j;this.duplicate=l;this.extend=function(a,c){a.prototype=j({},c.prototype,a.prototype);a.prototype.constructor=a}});
Z.$package("Z",function(f){var h=function(){},n=/this.\$super/,j=function(c,a){1===arguments.length&&(a=c,c={});a=a||{};if(!f.isFunction(a.init))a.init=h;var d=function(){return this.init.apply(this,arguments)},b=c.extend;if(b){if("interface"===b.type&&f.isArray(b.methods)&&f.isFunction(b.checkImplements))throw Error("can not extend a interface!");var m=b.prototype.init,g=a.init,j=f.duplicate(b.prototype);delete j.init;var b=d.prototype=f.merge({},b.prototype,a),i,l,k;for(k in j)i=b[k],l=j[k],f.isFunction(l)&&
f.isFunction(i)&&n.test(i)&&(b[k]=function(a,c){return function(){var b=this.$super;this.$super=a;c.apply(this,arguments);this.$super=b}}(l,i));d.prototype.init=function(){var a=f.duplicate(arguments);m.apply(this,a);this.$static=d;g.apply(this,arguments)}}else g=a.init,d.prototype=a,d.prototype.init=function(){this.$static=d;g.apply(this,arguments)};d.prototype.constructor=d;d.type="class";d.className=c.name||"anonymous";if(j=c["implements"]){k=[];for(var o in j)b=j[o].checkImplements(d.prototype),
k=k.concat(b);if(k.length)throw Error("the '"+d.className+"' class hasn't implemented the interfaces's methods . ["+k+"]");}c.statics&&f.merge(d,c.statics);return d},l=function(a){var e=[],d,b;for(b in this.methods)d=a[this.methods[b]],(!d||!f.isFunction(d))&&e.push(methods[b]);return e},a=function(a,e){1===arguments.length&&(e=a,a={});var d=function(){throw Error("the interface can not be Instantiated!");};d.type="interface";d.interfaceName=a.name||"anonymous";d.methods=e;d.checkImplements=l;return d};
this.define=function(c,e,d){var b=Array.prototype.slice.call(arguments,1);if("class"===c)return j.apply(this,b);if("interface"===c)return a.apply(this,b)};this.$class=j;this.$interface=a});
Z.$package("Z.message",function(f){var h,n=0,j=function(){if(!h&&(h=document.createElement("div"),!document.createEvent))h.style.cssText="position: absolute; top: -9999em; left: -9999em; width: 0px; height: 0px;",document.body.appendChild(h);return h},l=function(a,e,d){var b,f,g,h;if(2>arguments.length)throw Error("addListener arguments not enough");2===arguments.length&&(d=e,e=a,a=window);if(!a.__listeners)a.__listeners={},a.__listenerId=+new Date+""+n++;g=a.__listeners;h=a.__listenerId;if(g[e])for(f in g[e]){if(b=
g[e][f],b.func===d)return!1}else g[e]=[];f=j();f.addEventListener?(b=function(a){d.apply(window,a.params)},f.addEventListener(h+"-"+e,b,!1)):(b=function(a){var a=window.event,b=a.params.pop();e===a.params[1]&&b===h&&d.apply(window,a.params)},f.attachEvent("onpropertychange",b));b={func:d,wrapFunc:b};g[e].push(b);return!0},a=function(a,e,d){var b,f,g,h;if(2>arguments.length)throw Error("removeListener arguments not enough");2===arguments.length&&(d=e,e=a,a=window);g=a.__listeners;h=a.__listenerId;
if(!g||!g[e])return!1;f=j();for(var i in g[e])if(b=g[e][i],b.func===d)return g[e].slice(i,1),f.removeEventListener?f.removeEventListener(h+"-"+e,b.wrapFunc,!1):f.detachEvent("onpropertychange",b.wrapFunc),!0;return!1};this.on=this.addListener=l;this.off=this.removeListener=a;this.notify=function(a,e,d){var b,h,g,l;1===arguments.length?(e=a,a=window):2===arguments.length&&f.isString(a)&&(d=e,e=a,a=window);f.debug("notify message: "+e);g=a.__listeners;l=a.__listenerId;if(!g||!g[e])return!1;b=j();document.createEvent?
(h=document.createEvent("Events"),h.initEvent(l+"-"+e,!1,!1),h.params=[d,e],b.dispatchEvent(h)):(h=document.createEventObject("onpropertychange"),h.params=[d,e,l],b.fireEvent("onpropertychange",h));return 0!==g[e].length}});
