(function(e){var g={UNDEFINED:0,BUILDED:1,LOADED:2,INITED:3},m={},j={},l=0,a=function(a){if(m[a])return m[a];var a=a.split("."),f=window,b;for(b in a){if(!(a[b]in f))return e;f=f[a[b]]}return f},f=function(f){return(f=a(f))?f.packageStatus:g.UNDEFINED},b=function(f,h,c){"string"===typeof f&&(f=a(f));var i={},e=a("Z");if(h)for(var k in h)i[k]=a(h[k]);c&&c.call(f,e,i);f.packageStatus=g.INITED;f=f.packageName;if(h=j[f]){for(i=0;i<h.length;i++)c=h[i],d(c.requirePackages)&&b(c.packageName,c.requirePackages,
c.constructor);delete j[f]}},d=function(a){if(!a)return!0;var b,c;for(c in a)if(b=a[c],f(b)!==g.INITED)return!1;return!0},c=function(){var f,a,c;f=arguments[0];3===arguments.length?(a=arguments[1],c=arguments[2]):2===arguments.length?c=arguments[1]:(f="Z.anonymous."+l++,c=arguments[0]);var i;i=f;var e=m[i];if(!e){var e=window,k=i.split("."),n;for(n in k)k[n]in e||(e[k[n]]={}),e=e[k[n]];m[i]=e}if(!("packageName"in e))e.packageName=i;if(!("packageStatus"in e))e.packageStatus=g.BUILDED;i=e;if(i.packageStatus===
g.BUILDED)i.packageStatus=g.LOADED;if(a&&!d(a))for(var p in a)i=a[p],j[i]||(j[i]=[]),j[i].push({packageName:f,requirePackages:a,constructor:c});else b(i,a,c)};c("Z",function(b){b.PACKAGE_STATUS=g;b.$package=c;b.getPackage=a;b.getPackageStatus=f})})();
Z.$package("Z",function(e){this.debug=function(a){window.console&&(console.debug?console.debug(a):console.log(a))};var g=Object.prototype.toString;this.is=function(a,f){var b=g.call(f).slice(8,-1);return void 0!==f&&null!==f&&b===a};this.isString=function(a){return"[object String]"===g.call(a)};this.isArray=Array.isArray||function(a){return"[object Array]"===g.call(a)};this.isArguments=function(a){return"[object Arguments]"===g.call(a)};this.isObject=function(a){return"[object Object]"===g.call(a)};
this.isFunction=function(a){return"[object Function]"===g.call(a)};this.isUndefined=function(a){return"[object Undefined]"===g.call(a)};this.isBoolean=function(a){return"[object Boolean]"===g.call(a)};this.isNumber=function(a){return"[object Number]"===g.call(a)};this.isEmpty=function(a){if(a){if(this.isArray(a))return!!a.length;for(var f in a)return!1;return!0}return!1};var m=this.isSameObject=function(a,f,b){if(a===f||!a&&!f)return!0;for(var d in a)if(a.hasOwnProperty(d))if(e.isObject(a[d])&&e.isObject(f[d])&&
b){if(!m(a[d],f[d],b))return!1}else if(a[d]!==f[d])return!1;return!0},j=function(a,f,b){for(var d=arguments,c,g=1;g<d.length;g++){c=d[g];for(var h in c)a[h]=e.isArray(c[h])?c[h].concat():e.isObject(c[h])?a[h]&&e.isArray(a[h])?j({},c[h]):j({},a[h],c[h]):c[h]}return a},l=function(a){if(e.isArray(a))return a.concat();if(e.isArguments(a)){for(var f=[],b=0,d;d=a[b];b++)f.push(l(d));return f}return e.isObject(a)?j({},a):a};this.merge=j;this.duplicate=l;this.extend=function(a,f){a.prototype=j({},f.prototype,
a.prototype);a.prototype.constructor=a}});
Z.$package("Z",function(e){var g=function(){},m=/this.\$super/,j=function(a,b){1===arguments.length&&(b=a,a={});b=b||{};if(!e.isFunction(b.init))b.init=g;var d=function(){return this.init.apply(this,arguments)},c=a.extend;if(c){if("interface"===c.type&&e.isArray(c.methods)&&e.isFunction(c.checkImplements))throw Error("can not extend a interface!");var o=c.prototype.init,h=b.init,j=e.duplicate(c.prototype);delete j.init;var c=d.prototype=e.merge({},c.prototype,b),i,l,k;for(k in j)i=c[k],l=j[k],e.isFunction(l)&&
e.isFunction(i)&&m.test(i)&&(c[k]=function(a,f){return function(){var b=this.$super;this.$super=a;f.apply(this,arguments);this.$super=b}}(l,i));d.prototype.init=function(){var a=e.duplicate(arguments);o.apply(this,a);this.$static=d;h.apply(this,arguments)}}else h=b.init,d.prototype=b,d.prototype.init=function(){this.$static=d;h.apply(this,arguments)};d.prototype.constructor=d;d.type="class";d.className=a.name||"anonymous";if(j=a["implements"]){k=[];for(var n in j)c=j[n].checkImplements(d.prototype),
k=k.concat(c);if(k.length)throw Error("the '"+d.className+"' class hasn't implemented the interfaces's methods . ["+k+"]");}a.statics&&e.merge(d,a.statics);return d},l=function(a){var b=[],d,c;for(c in this.methods)d=a[this.methods[c]],(!d||!e.isFunction(d))&&b.push(methods[c]);return b},a=function(a,b){1===arguments.length&&(b=a,a={});var d=function(){throw Error("the interface can not be Instantiated!");};d.type="interface";d.interfaceName=a.name||"anonymous";d.methods=b;d.checkImplements=l;return d};
this.define=function(f,b,d){var c=Array.prototype.slice.call(arguments,1);if("class"===f)return j.apply(this,c);if("interface"===f)return a.apply(this,c)};this.$class=j;this.$interface=a});
Z.$package("Z.message",function(e){var g,m=0,j=function(){if(!g&&(g=document.createElement("div"),!document.createEvent))g.style.cssText="position: absolute; top: -9999em; left: -9999em; width: 0px; height: 0px;",document.body.appendChild(g);return g},l=function(a,b,d){var c,e,h,g;if(2>arguments.length)throw Error("addListener arguments not enough");2===arguments.length&&(d=b,b=a,a=window);if(!a.__listeners)a.__listeners={},a.__listenerId=+new Date+""+m++;h=a.__listeners;g=a.__listenerId;if(h[b])for(e in h[b]){if(c=
h[b][e],c.func===d)return!1}else h[b]=[];e=j();e.addEventListener?(c=function(a){d.apply(window,a.params)},e.addEventListener(g+"-"+b,c,!1)):(c=function(a){var a=window.event,c=a.params.pop();b===a.params[1]&&c===g&&d.apply(window,a.params)},e.attachEvent("onpropertychange",c));c={func:d,wrapFunc:c};h[b].push(c);return!0},a=function(a,b,d){var c,e,h,g;if(2>arguments.length)throw Error("removeListener arguments not enough");2===arguments.length&&(d=b,b=a,a=window);h=a.__listeners;g=a.__listenerId;
if(!h||!h[b])return!1;e=j();for(var i in h[b])if(c=h[b][i],c.func===d)return h[b].slice(i,1),e.removeEventListener?e.removeEventListener(g+"-"+b,c.wrapFunc,!1):e.detachEvent("onpropertychange",c.wrapFunc),!0;return!1};this.on=this.addListener=l;this.off=this.removeListener=a;this.notify=function(a,b,d){var c,g,h,l;1===arguments.length?(b=a,a=window):2===arguments.length&&e.isString(a)&&(d=b,b=a,a=window);e.debug("notify message: "+b);h=a.__listeners;l=a.__listenerId;if(!h||!h[b])return!1;c=j();document.createEvent?
(g=document.createEvent("Events"),g.initEvent(l+"-"+b,!1,!1),g.params=[d,b],c.dispatchEvent(g)):(g=document.createEventObject("onpropertychange"),g.params=[d,b,l],c.fireEvent("onpropertychange",g));return 0!==h[b].length}});
