(function(e){var i={UNDEFINED:0,BUILDED:1,LOADED:2,INITED:3},m=this;if("undefined"!=typeof module)module.exports=m={};var j={},k={},a=0,d=function(a){if(j[a])return j[a];var a=a.split("."),b=m,d;for(d in a){if(!(a[d]in b))return e;b=b[a[d]]}return b},c=function(a){return(a=d(a))?a.packageStatus:i.UNDEFINED},b=function(a,c,e){"string"===typeof a&&(a=d(a));var g={},h=d("Z");if(c)for(var j in c)g[j]=d(c[j]);e&&e.call(a,h,g);a.packageStatus=i.INITED;a=a.packageName;if(c=k[a]){for(g=0;g<c.length;g++)e=
c[g],f(e.requirePackages)&&b(e.packageName,e.requirePackages,e.constructor);delete k[a]}},f=function(a){if(!a)return!0;var b,d;for(d in a)if(b=a[d],c(b)!==i.INITED)return!1;return!0},n=function(){var d,c,e;d=arguments[0];3===arguments.length?(c=arguments[1],e=arguments[2]):2===arguments.length?e=arguments[1]:(d="Z.anonymous."+a++,e=arguments[0]);var g;g=d;var h=j[g];if(!h){var h=m,n=g.split("."),p;for(p in n)n[p]in h||(h[n[p]]={}),h=h[n[p]];j[g]=h}if(!("packageName"in h))h.packageName=g;if(!("packageStatus"in
h))h.packageStatus=i.BUILDED;g=h;if(g.packageStatus===i.BUILDED)g.packageStatus=i.LOADED;if(c&&!f(c))for(var r in c)g=c[r],k[g]||(k[g]=[]),k[g].push({packageName:d,requirePackages:c,constructor:e});else b(g,c,e)};n("Z",function(a){a.PACKAGE_STATUS=i;a.$package=n;a.getPackage=d;a.getPackageStatus=c;Z=a})})();
Z.$package("Z",function(e){this.debug=function(a){"undefined"!=typeof console&&(console.debug?console.debug(a):console.log(a))};var i=Object.prototype.toString;this.is=function(a,d){var c=i.call(d).slice(8,-1);return void 0!==d&&null!==d&&c===a};this.isString=function(a){return"[object String]"===i.call(a)};this.isArray=Array.isArray||function(a){return"[object Array]"===i.call(a)};this.isArguments=function(a){return"[object Arguments]"===i.call(a)};this.isObject=function(a){return"[object Object]"===
i.call(a)};this.isFunction=function(a){return"[object Function]"===i.call(a)};this.isUndefined=function(a){return"[object Undefined]"===i.call(a)};this.isBoolean=function(a){return"[object Boolean]"===i.call(a)};this.isNumber=function(a){return"[object Number]"===i.call(a)};this.isEmpty=function(a){if(a){if(this.isArray(a))return!!a.length;for(var d in a)return!1;return!0}return!1};var m=this.isSameObject=function(a,d,c){if(a===d||!a&&!d)return!0;for(var b in a)if(a.hasOwnProperty(b))if(e.isObject(a[b])&&
e.isObject(d[b])&&c){if(!m(a[b],d[b],c))return!1}else if(a[b]!==d[b])return!1;return!0},j=function(a,d,c){for(var b=arguments,f,i=1;i<b.length;i++){f=b[i];for(var l in f)a[l]=e.isArray(f[l])?f[l].concat():e.isObject(f[l])?a[l]&&e.isArray(a[l])?j({},f[l]):j({},a[l],f[l]):f[l]}return a},k=function(a){if(e.isArray(a))return a.concat();if(e.isArguments(a)){for(var d=[],c=0,b;b=a[c];c++)d.push(k(b));return d}return e.isObject(a)?j({},a):a};this.merge=j;this.duplicate=k;this.extend=function(a,d){a.prototype=
j({},d.prototype,a.prototype);a.prototype.constructor=a}});
Z.$package("Z",function(e){var i=function(){},m=/this.\$super/,j=function(a,c){1===arguments.length&&(c=a,a={});c=c||{};if(!e.isFunction(c.init))c.init=i;var b=function(){return this.init.apply(this,arguments)},f=a.extend;if(f){if("interface"===f.type&&e.isArray(f.methods)&&e.isFunction(f.checkImplements))throw Error("can not extend a interface!");var j=f.prototype.init,l=c.init,k=e.duplicate(f.prototype);delete k.init;var f=b.prototype=e.merge({},f.prototype,c),o,g,h;for(h in k)o=f[h],g=k[h],e.isFunction(g)&&
e.isFunction(o)&&m.test(o)&&(f[h]=function(a,b){return function(){var d=this.$super;this.$super=a;b.apply(this,arguments);this.$super=d}}(g,o));b.prototype.init=function(){var a=e.duplicate(arguments);j.apply(this,a);this.$static=b;l.apply(this,arguments)}}else l=c.init,b.prototype=c,b.prototype.init=function(){this.$static=b;l.apply(this,arguments)};b.prototype.constructor=b;b.type="class";b.className=a.name||"anonymous";if(k=a["implements"]){h=[];for(var q in k)f=k[q].checkImplements(b.prototype),
h=h.concat(f);if(h.length)throw Error("the '"+b.className+"' class hasn't implemented the interfaces's methods . ["+h+"]");}a.statics&&e.merge(b,a.statics);return b},k=function(a){var c=[],b,f;for(f in this.methods)b=a[this.methods[f]],(!b||!e.isFunction(b))&&c.push(methods[f]);return c},a=function(a,c){1===arguments.length&&(c=a,a={});var b=function(){throw Error("the interface can not be Instantiated!");};b.type="interface";b.interfaceName=a.name||"anonymous";b.methods=c;b.checkImplements=k;return b};
this.define=function(d,c,b){var e=Array.prototype.slice.call(arguments,1);if("class"===d)return j.apply(this,e);if("interface"===d)return a.apply(this,e)};this.$class=j;this.$interface=a});
